; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:arduino_nano_esp32]
[env:arduino_nano_esp32]
platform       = espressif32
board          = arduino_nano_esp32
framework      = arduino

build_unflags  = -std=gnu++11
build_flags    =
    -std=gnu++17
    -D ARDUINO_USB_MODE=0
    -D ARDUINO_USB_CDC_ON_BOOT=1


monitor_filters= esp32_exception_decoder
monitor_flags = --dtr

;--------------------------
;upload_protocol = esptool
;---------------------------
;   For SPIFFS, esptool programmer must be used.
;   >> This involves some weird steps to write '/data' directory to SPIFFS
;       1. Make sure nothing opened in port (Arduino IDE),
;       2. Have to click 'Upload Filesystem Image'. THIS WILL FAIL, but it's cool,
;       3. Click 'Upload Filesystem Image' again, this time it should work.
;       4. Press 'RST' button on board,
;       5. ** DON'T FORGET ** comment 'upload_protocol' out to use regular DFU. Next time you upload,
;           it may fail. Just try to upload again.
;     Now, we can host HTML/JS/CSS files and not tinker with condensing it all into a const char *
;       via PROGMEM. (Yeah, not sure it's worth it...)

board_build.filesystem   = spiffs
board_build.partitions   = min_spiffs.csv
board_build.flash_mode   = dio

lib_deps =
    esp32async/ESPAsyncWebServer
    ESP32Async/AsyncTCP
    ArduinoJson